name: konekin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  carousel_slider: 4.2.1
  url_launcher: 6.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

